# Define the build settings

[[redirects]]
  # Catch-all rule for client-side routing
  from = "/*"
  to = "/index.html"
  status = 200

# Custom headers for static assets
[[headers]]
  for = "/assets/*" # Customize this based on your assets path
  [headers.values]
    Access-Control-Allow-Origin = "*"


[[headers]]
for = "/*.js"
[headers.values]
Content-Type = "application/javascript"


